# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victor Stabile
email: vmstabile@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Founder & CTO da Liber Capital. Engenheiro Físico.
  Entusiasta da cultura hacker, criptografia, Bitcoin, IA e exploração espacial.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victorstabile.com" # the base hostname & protocol for your site
linkedin_username: stabile
github_username:  vstabile
twitter_username: vmstabile

# Build settings
markdown: kramdown
permalink: /:title
